services:
  backend:
    restart: on-failure
    container_name: ricotta-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./api:/usr/src/app/api/:z
      - datadb:/data/db
    ports:
      - "9124:9124"

  frontend:
    container_name: ricotta-frontend
    restart: on-failure
    image: registry.digitalocean.com/my-virtual-machine-registry/ricotta-frontend:latest
    ports:
      - "8008:8008"
    volumes:
      - ./client:/usr/src/app/client/:z
      - /usr/src/app/client/node_modules
    environment:
      - VITE_API_SERVER=https://ricotta-api.holeytriangle.com

volumes:
  datadb:
