# ---------------------------------------
# Build frontend
FROM node:18-bookworm-slim as frontend2

WORKDIR /usr/src/app/client

COPY ./client/package.json ./client/pnpm-lock.yaml ./
COPY ./client /usr/src/app/client/
COPY ricotta.env /usr/src/app/client/.env

RUN npm install --only=production && npm cache clean --force
RUN npm install --global typescript
RUN npm install --global pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm run build

EXPOSE 8008
CMD ["pnpm", "run", "host"]
